spring:
  application:
    name: phonebooker
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "YOUR-POSTGRESQL_USERNAME"
    password: "YOUR-POSTGRESQL_PASSWORD"
    url: "YOUR-POSTGRESQL_URL"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

fonoapi:
  url: "https://fonoapi.freshpixl.com/v1/"
  token: "xxxxx"

